👷 Test for coverage change in PRs

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -49,12 +49,12 @@ jobs:
       - name: Install dependencies
         run: bun install --frozen-lockfile
       - name: Run tests
-        run: npm test
+        run: bun run test
       - name: Save aside coverage report
         if: ${{ always() }}
         uses: actions/upload-artifact@v4
         with:
-          name: vitest-report
+          name: vitest-report-head
           path: ./coverage
       - name: Deploy results to Github Pages
         if: ${{ !cancelled() }}
@@ -128,8 +128,31 @@ jobs:
           else
             echo "All fr.json keys are used in the codebase"
           fi
-  coverage:
-    name: Coverage
+
+  get-base-branch-coverage:
+    name: Get base branch coverage
+    runs-on: ubuntu-latest
+    if: github.event_name == 'pull_request'
+    steps:
+      - uses: actions/checkout@v5
+        with:
+          ref: ${{ github.event.pull_request.base.ref }}
+      - uses: oven-sh/setup-bun@v2
+        with:
+          bun-version-file: .bun-version
+      - name: Install dependencies
+        run: bun install --frozen-lockfile
+      - name: Run tests
+        run: bun run test
+      - name: Save aside coverage report
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: vitest-report-base
+          path: ./coverage
+
+  upload-coverage-report:
+    name: Coverage report
     runs-on: ubuntu-latest
     needs: test
     environment:
@@ -140,13 +163,44 @@ jobs:
       - name: Get coverage report
         uses: actions/download-artifact@v5
         with:
-          name: vitest-report
+          name: vitest-report-head
           path: ./coverage
       - name: Deploy coverage report to Github Pages
-        if: ${{ !cancelled() }}
+        if: always()
         uses: rossjrw/pr-preview-action@v1
         id: deploy-preview
         with:
           source-dir: ./coverage
           umbrella-dir: _coverage
           comment: false
+
+  compare-coverage:
+    name: Compare coverage
+    runs-on: ubuntu-latest
+    needs: [test, get-base-branch-coverage]
+    if: github.event_name == 'pull_request'
+    steps:
+      - uses: actions/checkout@v5
+      - uses: actions/download-artifact@v5
+        with:
+          name: vitest-report-head
+          path: ./coverage
+      - uses: actions/download-artifact@v5
+        with:
+          name: vitest-report-base
+          path: ./base-coverage
+      - name: Compare coverage difference
+        run: |
+          base_coverage=$(jq '.total.lines.pct' base-coverage/coverage-summary.json)
+          head_coverage=$(jq '.total.lines.pct' coverage/coverage-summary.json)
+          echo "Base branch coverage: $base_coverage%"
+          echo "Head branch coverage: $head_coverage%"
+          diff=$(echo "$head_coverage - $base_coverage" | bc)
+          diff=$(printf "%.2f" "$diff")
+          echo "Coverage difference: $diff%"
+          if (( $(echo "$diff < -0.5" | bc -l) )); then
+            echo "Coverage decreased by more than 0.5%. Failing the check."
+            exit 1
+          else
+            echo "Coverage difference is acceptable."
+          fi
