👩‍💻‍ Temporarily disable protocol regeneration

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -98,10 +98,35 @@ jobs:
       artifact: ${{ needs.build.outputs.artifact }}
       deploy: ${{ github.ref_name == 'main' }}
 
+  dont-merge-comment:
+    name: Check for presence of "do not merge" comment
+    if: github.event_name == 'pull_request'
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v6
+      - run: |
+          # Check for "XXX: DONT MERGE" in current source code
+          if git grep -q 'XXX: DONT MERGE'; then
+            echo "Found 'XXX: DONT MERGE' in source code. Failing the job."
+            exit 1
+          else
+            echo "No 'XXX: DONT MERGE' found in source code."
+          fi
+
   is-mergeable:
     if: github.event_name == 'pull_request' && !cancelled()
     name: Mergeable?
-    needs: [build, json-schema, lint, test, e2e, preview, electron, docker, bundlesize]
+    needs:
+      - build
+      - json-schema
+      - lint
+      - test
+      - e2e
+      - preview
+      - electron
+      - docker
+      - bundlesize
+      - dont-merge-comment
     runs-on: ubuntu-latest
     steps:
       - if: contains(needs.*.result, 'failure')
