🔀 Setup i18n (#471)

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -70,7 +70,36 @@ jobs:
       - name: Install dependencies
         run: npm ci
       - name: Check for clutter
-        run: npx knip
+        run: npm run check:clutter
+  i18n:
+    name: Check for untranslated messages
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+        with:
+          node-version: '22.17.1'
+      - name: Install dependencies
+        run: npm ci
+      - name: Check for untranslated messages
+        run: |
+          missing=()
+          for key in $(jq -r 'keys[]' messages/fr.json); do
+            value=$(jq -r --arg k "$key" '.[$k] // empty' messages/en.json)
+            if [[ -z "$value" ]]; then
+              missing+=("$key")
+            fi
+          done
+          if [ ${#missing[@]} -ne 0 ]; then
+            echo "Missing or empty keys in en.json:"
+            for key in "${missing[@]}"; do
+              fr_value=$(jq -r --arg k "$key" '.[$k]' messages/fr.json)
+              echo "- $key: $fr_value"
+            done
+            exit 1
+          else
+            echo "All fr.json keys are present and non-empty in en.json"
+          fi
   coverage:
     name: Coverage
     runs-on: ubuntu-latest
